### ISSUE TITLE
Allow GraphicalSurface.plot() to change plot color via arguments

### ISSUE THREAD

**Issue by zsteinberg** [flatsurf/sage-flatsurf#109]
It would be nice for GraphicalSurface.plot() to allow you to do things like `.plot(rgbcolor=(1,0,0), edgecolor=(0,1,0))` so that different surfaces could be color-coded. One way to do this might be to take some **kwargs and pass them to the internal polygon2d.plot() calls?

**Comment by saraedum** [comment]
So, I guess that `GraphicalSurface.plot()` but also `SimilaritySurface.plot()` could take `**kwargs` that are decoded as follows:

* well known options are just merged into the graphical surface options, e.g., a dict for `non_adjacent_edge_options` is merged into `GraphicalSurface.non_adjacent_edge_options`.
* prefixed options are merged into the corresponding options of the `GraphicalSurface`, e.g., `polygon_label_color` is setting `polygon_label_options["color"]`.
* everything else is merged into `GraphicalSurface.polygon_options`, e.g., `color="blue"` sets `polygon_options["color"]="blue"`.

This does not add anything new but probably makes plotting things much more convenient so we don't have to explicitly mutate the `GraphicalSurface` object which is a somewhat non-standard approach if you're coming from SageMath plotting imho.
