### ISSUE TITLE
Support e-antic

### ISSUE THREAD

**Issue by saraedum** [flatsurf/sage-flatsurf#11]
How would we best support coordinates given with e-antic (pyeantic) coordinates?

**Comment by saraedum** [comment]
I guess we could teach pyeantic to convert from/to elements of a number field with an embeding. Is that a good idea?

**Comment by videlec** [comment]
It is already tought in [sage_conversion.py](https://github.com/flatsurf/pyeantic/blob/master/src/pyeantic/sage_conversion.py). Or did you mean something else?

**Comment by saraedum** [comment]
A version with proper SageMath parents & elements is now in https://github.com/flatsurf/pyeantic/pull/26 (wip.)
