### ISSUE TITLE
Support exact-real

### ISSUE THREAD

**Issue by saraedum** [flatsurf/sage-flatsurf#12]
How can we support exact-real `Element` as coordinates? (depends on #11)

The interface should also provide:
* Provide something like map_lengths() on the level of polygons. This accepts a general map, e.g., one that maps an exact-real to a new random exact-real and records each value so that the mapping is done consistently. (This needs something like `x.randomize()` in `exactreal::RealNumber` to produce a real number in the same class of reals, i.e., with the same constraints.)

**Comment by videlec** [comment]
Right now, each polygon (class `ConvexPolygon`) has a parent (class `ConvexPolygons`). The latter handles the base ring and the element construction. It should be possible to construct new parents to handle more scalar types that behave like real numbers (Python integers, elements of `gmpy2`, `mpz_class`/`mpq_class`, `pyeantic`, `real-exact`, ...).

One problem is that the code assumes that the parent knows how to construct (Sage) vectors out of elements of the base ring. And in further methods these vectors are used to construct (Sage) matrices. Hence, each new parent should also have the ability to build vectors and 2x2 matrices and some of the code has to be adapted. But hopefully, this can come in a second step.

**Comment by videlec** [comment]
fixed in #49
