### ISSUE TITLE
Convex geometry of the hyperbolic plane

### ISSUE THREAD

**Issue by videlec** [flatsurf/sage-flatsurf#154]
This is a draft of notes that we took at a meeting in Bordeaux in early 2022. Please extend these notes.

---

Geometry on the hyperbolic plane is not really implemented in SageMath. It's needed for our implementation of #155. While it might eventually go upstream into SageMath, we want to first implement it in sage-flatsurf.

Here are some objects that we think we should implement:

```python
class flatsurf.geometry.HyperbolicPlane:
    # over a fixed base ring. Probably does nothing but store that base ring.
    
class flatsurf.geometry.HyperbolicHalfPlane:
    # implement sagemath containment for points
    
class flatsurf.geometry.HyperbolicPoint:
    
class flatsurf.geometry.HyperbolicPolytope:
    # intersection of half planes, as a list of edges.
    
class flatsurf.geometry.HyperbolicEdge:
```

It is not completely clear which hyperbolic model is the best to work with (probably the hyperboloid is more "linear").

**Comment by slel** [comment]
> Though a geodesic segment is not an intersection of half planes...

It is if you ask me.

**Comment by saraedum** [comment]
Superseded by #156 due to permission issues.
