### ISSUE TITLE
Add Prym eigenforms prototypes

### ISSUE THREAD

**Issue by sfreedman67** [flatsurf/sage-flatsurf#179]
I think the interface would mirror `flatsurf.translation_surfaces.mcmullen_genus2_prototype`, such as:

`flatsurf.translation_surfaces.lanneau_nguyen_genus3_prototype(w, h, t, e, base_ring=None)` 

for the S-shaped prototype in `H(4)`. The associated discriminant is now `D = e^2 + 8wh`.

We could also have `flatsurf.translation_surfaces.lanneau_nguyen_genus4_prototype(w, h, t, e, base_ring=None`, which is an X-shaped prototype in `H(6)`.

**Comment by saraedum** [comment]
See also #65.
