### ISSUE TITLE
GL2ROrbitClosure.dimension() off by a factor of 1/2?

### ISSUE THREAD

**Issue by sfreedman67** [flatsurf/sage-flatsurf#184]
When we initially ran `GL2ROrbitClosure(S).dimension()` we got `2` for the real dimension of the orbit closure, but should it have been `4`? @videlec @saraedum

**Comment by videlec** [comment]
The specification is not ideal but the answer is correct. The output is the dimension in `H^1(S, \Sigma; R)` not `H^1(S, \Sigma; C)`. Hence always half the real dimension of the manifold.

**Comment by videlec** [comment]
I will make it clearer in the documentation. Thanks for the report!
