### ISSUE TITLE
Fix note in SimilaritySurface doc

### ISSUE THREAD

**Issue by slel** [flatsurf/sage-flatsurf#21]
The note in the `SimilaritySurface` doc at

https://github.com/videlec/sage-flatsurf/blob/f3430a581d95c3b3c63846c1b2406e02f7b597b6/flatsurf/geometry/similarity_surface.py#L37

mentions

>         This class is abstract and should not be called directly. Instead you
>        can either use SimilaritySurface_from_polygons_and_identifications or
>        inherit from SimilaritySurface_generic and implement the methods:

but neither `SimilaritySurface_from_polygons_and_identifications`
nor `SimilaritySurface_generic` seem to exist (any longer?).

**Comment by videlec** [comment]
fixed in #23
