### ISSUE TITLE
Singular intersections of saddle connections

### ISSUE THREAD

**Issue by Julien-Boulanger** [flatsurf/sage-flatsurf#249]
It would be nice to implement a function which computes the algebraic intersection of two saddle connections (or closed curves which are unions of saddle connections if there are more than one singularity). For this, one would need to be able to compute the intersection of two saddle connections at a singular point.

**Comment by videlec** [comment]
The fastest is to compute the homology class of saddle connections (and their sum) and compute the algebraic intersection their. In other words, decompose any path as a formal sum of edges of the original polygons that define your surface.

Note that there are "two" algebraic intersections
- $H_1(S; \mathbb{Z}) \times H_1(S; \mathbb{Z}) \to \mathbb{Z})$
- $H_1(S, \Sigma; \mathbb{Z}) \times H_1(S \setminus \Sigma; \mathbb{Z}) \to \mathbb{Z})$

**Comment by saraedum** [comment]
@Julien-Boulanger implemented the basic algorithm here.
I'll try to merge this into #213.
[Algebraic_intersection_flatsurf.md](https://github.com/flatsurf/sage-flatsurf/files/13191475/Algebraic_intersection_flatsurf.md)

**Comment by saraedum** [comment]
@Julien-Boulanger I adapted your code for the branch in #211. It can now be tested there (let me know if you need help with this.)

It seems to work fine. However, one of the examples produces a different output for me. Your example was:

```py
    sage: from flatsurf import translation_surfaces
    sage: S = translation_surfaces.regular_octagon()
    sage: dict0 = {(0, 0):2, (0, 1):1, (0, 2):3, (0, 3):1, (0, 4):1, (0, 5):1, (0, 6):0, (0, 7):1}
    sage: dict1 = {(0, 0):1, (0, 1):2, (0, 2):1, (0, 3):1, (0, 4):2, (0, 5):3, (0, 6):4, (0, 7):3}
    sage: algebraic_intersection(dict_0,dict_1)
    1
```

However, when I run the following, I get -6 instead of 1.
```py
            sage: from flatsurf import translation_surfaces, SimplicialHomology
            sage: S = translation_surfaces.regular_octagon()
            sage: H = SimplicialHomology(S)

            sage: a = 2 * H((0, 0)) + H((0, 1)) + 3 * H((0, 2)) + H((0, 3)) + H((0, 4)) + H((0, 5)) + H((0, 7))
            sage: b = H((0, 0)) + 2 * H((0, 1)) + H((0, 2)) + H((0, 3)) + 2 * H((0, 4)) + 3 * H((0, 5)) + 4 * H((0, 6)) + 3 * H((0, 7))
            sage: a.algebraic_intersection(b)
```

**Comment by Julien-Boulanger** [comment]
That's my fault I checked again and it should indeed be a -6 !

**Comment by saraedum** [comment]
This was included in #291.

**Comment by saraedum** [comment]
But the interface for saddle connections is still missing I think.

**Comment by videlec** [comment]
> But the interface for saddle connections is still missing I think.

What do you think it should be : `surface.homology()(saddle_connection)`? `saddle_connection.homology()`? both? something else?

**Comment by saraedum** [comment]
> > But the interface for saddle connections is still missing I think.
> 
> What do you think it should be : `surface.homology()(saddle_connection)`? `saddle_connection.homology()`? both? something else?

I think it should be `homology(saddle_connection)`. I don't like `saddle_connection.homology()` because the homology is not unique.

**Comment by videlec** [comment]
See #308

**Comment by saraedum** [comment]
@videlec is there anything left to do here?

**Comment by videlec** [comment]
Looks good. Thanks.
