### ISSUE TITLE
Non convex polygons and flat disks

### ISSUE THREAD

**Issue by videlec** [flatsurf/sage-flatsurf#25]
It would be nice to support the construction of non-convex polygons and more generally flat disks (ie compact translation surface structure on the disc with boundary made of finitely many segments). Right now the user must provide a decomposition into non-convex polygons which is somehow a pain. The naive algorithm to triangulate non-convex polygons and flat disks should be good enough for most purposes.

**Comment by wphooper** [comment]
I guess the request is a bit unclear. Are you suggesting that we enable
building surfaces from such pieces or that we change the basic building
blocks of the program to allow objects such as non-convex polygons? I'd
support the former, but actually doing programming involving non-convex
polygons would be very painful. (Even geodesic flow in a non-convex polygon
is painful.)

Assuming the suggestion is to allow surfaces be built in this way, I would
suggest more generally supporting subsurfaces with polygonal boundaries.
For example, slit tori can be used to build surfaces, but their
decomposition into convex polygons is non-obvious.

**Comment by videlec** [comment]
I definitely don't want to compute the geodesic flow in a flat disk before actually computing a decomposition into convex polygons. This is not a proposal to change that. On the other hand, many operations are easily doable on such model (ramified coverings, homology computations, etc). But the proposal is mainly about user input.

My plan is to make it easy to build any kind of surfaces with `sage-flatsurf`. And, as soon as any serious computation is required, switch to https://github.com/flatsurf/flatsurf.

**Comment by videlec** [comment]
More concrete proposal at #26 (work in progress).

**Comment by wphooper** [comment]
You didn't like the subsurface idea? Non-convex polygons and "flat disks"
can be thought of as special cases.

The plan to switch off from sage-flatsurf to flatsurf when appropriate
sounds good to me.

**Comment by videlec** [comment]
As mathematical objects, yes surfaces with boundaries are special cases of non-convex polygons. But the only reasonable way I know to build a surface is via simplicial decomposition which involves in some ways polygons.

My main motivation to introduce non-convex polygons is to get rid of 2pi conical singularities. Going through an intermediate step with non-convex polygon is I think the easiest.

**Comment by videlec** [comment]
I discuss surface with boundary in #27. Tell me what you think.

**Comment by wphooper** [comment]
I just want to make one minor comment on "flat disks". There are examples of curves which bound multiple disks, e.g., Milnor's doodle. I guess our code would need to decide if a loop (given by a cycle of edge vectors) bounds a single flat disk, and return that flat disk as a decomposition into polygons if so. This seems sort of painful for a feature that might not get used.

**Comment by videlec** [comment]
Does Milnor's doodle bounds multiple **flat** disks?

**Comment by wphooper** [comment]
Yes, and if you take a polygonal approximation, you'd get multiple disks with polygonal (piecewise-linear) boundary. See [Figure 6 from this article](https://www.semanticscholar.org/paper/Self-overlapping-curves%3A-Analysis-and-applications-Mukherjee/9d44d374622a26c35a62c0e606bf45c956c10014).

**Comment by videlec** [comment]
Thanks for the reference!

Do you know if there is any reasonable parametrization for the space of flat disks (let say with fixed number of segments on the boundary)? As you pointed out, the boundary is not.

**Comment by saraedum** [comment]
Since #26 has been merged. Can this issue be closed?

**Comment by videlec** [comment]
I think we can. For flat disks, I guess the only way is to go through a triangulation.
