### ISSUE TITLE
Define points on flat surfaces with boundary

### ISSUE THREAD

**Issue by KaiFu2210** [flatsurf/sage-flatsurf#275]
Given a flat surface S by pairing edges of polygons,  make the function
 "S.point()" work for points on the boundary of the surface.

**Comment by videlec** [comment]
Could you write down an explicit example in the issue description?

**Comment by KaiFu2210** [comment]
> Could you write down an explicit example that fails in the issue description?

Sure.

Example:
Let S be a flat surface defined as follows:
p0 = polygons(vertices = [(0,0), (-1, -1), (1,0)])
p1 = polygons(vertices = [(0,0), (0, 1), (-1,-1)])
S = MutableOrientedSimilaritySurface(QQ)
S.add_polygon(p0)
S.add_polygon(p1)
S.glue((0,0),(1,2))
S.set_immutable()
S becomes a translation surface with boundary built from 2 triangles.
However, we cannot define S.point(0,(0,0)), which is a point on the bounday of S.
