### ISSUE TITLE
enhance `erase_marked_points`

### ISSUE THREAD

**Issue by videlec** [flatsurf/sage-flatsurf#29]
Thanks to 806d80897f05a1b5eabe59fc56ace646a0c21e60 we now have a function to remove marked points. But
- it does not work in all cases (see the `NotImplementedError` in the method)
- the name `erase_marked_points` is perhaps not the best one (I took it because of what I did in `surface_dynamics`)

```
sage: import flatsurf
....: for a in range(1,10):
....:     for b in range(1,a):
....:         for c in range(1,b):
....:             T = flatsurf.polygons.triangle(a,b,c)
....:             S = flatsurf.similarity_surfaces.billiard(T)
....:             S = S.minimal_cover("translation")
....:             try:
....:                 _ = S.erase_marked_points()
....:             except NotImplementedError:
....:                 print(a,b,c)
3 2 1
4 3 1
5 4 1
6 4 2
6 5 1
7 6 1
8 6 2
8 7 1
9 6 3
9 8 1
```

**Comment by saraedum** [comment]
The `NotImplementedError` does not occur anymore.

**Comment by saraedum** [comment]
What should the name be?

**Comment by saraedum** [comment]
Closing this one. Feel free to reopen. I think the name is okay and the few users of sage-flatsurf are probably used to it by now ;)
