### ISSUE TITLE
Inconsistency in orbit closure dimensions

### ISSUE THREAD

**Issue by saraedum** [flatsurf/sage-flatsurf#55]
This is probably only broken with the changes in #51.

For the unfolding of the 1-1-1-1 quadrilateral, `billiard_unfolding_stratum_dimension('half-translation', marked_points=True)` gives an upper bound on the orbit closure dimension of 2. However, GL2ROrbitClosure finds that there are at least 3 dimension.

Similarly for 1-1-1-2-7 (7 vs 6), 1-1-1-3-6 (7 vs 6), 1-1-2-3-5 (7 vs 6.)

**Comment by saraedum** [comment]
@videlec How does the 1,1,1,1 quadrilateral get unfolded? Does it actually end up with 2 marked points so dimension 3 is correct?

**Comment by videlec** [comment]
For 1,1,1,1 we have a rectangle. The unfolding is a torus with 4 marked points and the dimension of the ambient stratum is 5. This is correctly computed by
```
sage: from flatsurf import EquiangularPolygons
sage: EquiangularPolygons(1,1,1,1).billiard_unfolding_stratum_dimension(marked_points=True)
5
```
However, the orbit closure in this situation has only (complex) dimension 2 because the marked points are exactly the 2-torsion points of the torus (that are preserved under GL(2,R)-action).

**Comment by videlec** [comment]
In other words, in the 1,1,1,1 case keeping or removing the marked points should not make a difference on the orbit-closure.

**Comment by saraedum** [comment]
So, I don't understand why this is happening.

```
sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf
sage: from flatsurf import EquiangularPolygons
sage: from pyexactreal import ExactReals  # optional: exactreal
sage: E = EquiangularPolygons(1, 1, 1, 1)
sage: R = ExactReals(E.base_ring())  # optional: exactreal
sage: T = E(R(1), R.random_element())  # optional: exactreal
sage: S = similarity_surfaces.billiard(T)  # optional: exactreal
sage: S = S.minimal_cover(cover_type="translation")  # optional: exactreal
sage: O = GL2ROrbitClosure(S); O  # optional: exactreal, pyflatsurf
GL(2,R)-orbit closure of dimension at least 2 in H_1(0^4) (ambient dimension 5)
sage: for decomposition in O.decompositions(2):  # optional: exactreal, pyflatsurf
....:     O.update_tangent_space_from_flow_decomposition(decomposition)
....:     if O.dimension() == E.billiard_unfolding_stratum('half-translation').dimension(): break
sage: O  # optional: exactreal, pyflatsurf
GL(2,R)-orbit closure of dimension at least 5 in H_1(0^4) (ambient dimension 5)
sage: E.billiard_unfolding_stratum('half-translation').dimension()
2
```

**Comment by saraedum** [comment]
I guess that means the we have a bug in `update_tangent_space_from_flow_decomposition`?

**Comment by videlec** [comment]
`E.billiard_unfolding_stratum('half-translation')` would better be replaced here by `E.billiard_unfolding_stratum('half-translation', marked_points=True)`.

I agree that most probably, `update_tangent_space_from_flow_decomposition` is wrong. And I even suspect `Decomposition.cylinder_deformation_subspace`.

**Comment by videlec** [comment]
BTW, this example fails for me with
```
sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf 
sage: from flatsurf import EquiangularPolygons 
sage: from pyexactreal import ExactReals  # optional: exactreal 
sage: E = EquiangularPolygons(1, 1, 1, 1) 
sage: R = ExactReals(E.base_ring())  # optional: exactreal 
sage: T = E(R(1), R.random_element())  # optional: exactreal                                                                                                                                                  
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-f3183ca702e7> in <module>
      4 E = EquiangularPolygons(Integer(1), Integer(1), Integer(1), Integer(1))
      5 R = ExactReals(E.base_ring())  # optional: exactreal
----> 6 T = E(R(Integer(1)), R.random_element())  # optional: exactreal

~/programming/flatsurf/sage-flatsurf/flatsurf/geometry/polygon.py in __call__(self, normalized, base_ring, *lengths)
   2240                 vertices.append(v)
   2241             s, t = vector(vertices[0] - vertices[n - 2]) * matrix([slopes[-1], slopes[n - 2]]).inverse()
-> 2242             assert vertices[0] - s * slopes[-1] == vertices[n - 2] + t * slopes[n - 2]
   2243             if s <= 0 or t <= 0:
   2244                 raise ValueError("the provided lengths do not give rise to a polygon")

AssertionError: 
```

**Comment by saraedum** [comment]
> E.billiard_unfolding_stratum('half-translation') would better be replaced here by E.billiard_unfolding_stratum('half-translation', marked_points=True).

Aren't these the same?

**Comment by saraedum** [comment]
> BTW, this example fails for me with
> 
> ```
> sage: from flatsurf import GL2ROrbitClosure  # optional: pyflatsurf 
> sage: from flatsurf import EquiangularPolygons 
> sage: from pyexactreal import ExactReals  # optional: exactreal 
> sage: E = EquiangularPolygons(1, 1, 1, 1) 
> sage: R = ExactReals(E.base_ring())  # optional: exactreal 
> sage: T = E(R(1), R.random_element())  # optional: exactreal                                                                                                                                                  
> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> <ipython-input-1-f3183ca702e7> in <module>
>       4 E = EquiangularPolygons(Integer(1), Integer(1), Integer(1), Integer(1))
>       5 R = ExactReals(E.base_ring())  # optional: exactreal
> ----> 6 T = E(R(Integer(1)), R.random_element())  # optional: exactreal
> 
> ~/programming/flatsurf/sage-flatsurf/flatsurf/geometry/polygon.py in __call__(self, normalized, base_ring, *lengths)
>    2240                 vertices.append(v)
>    2241             s, t = vector(vertices[0] - vertices[n - 2]) * matrix([slopes[-1], slopes[n - 2]]).inverse()
> -> 2242             assert vertices[0] - s * slopes[-1] == vertices[n - 2] + t * slopes[n - 2]
>    2243             if s <= 0 or t <= 0:
>    2244                 raise ValueError("the provided lengths do not give rise to a polygon")
> 
> AssertionError: 
> ```

That's really odd. Are you sure you have https://github.com/flatsurf/exact-real/releases/tag/1.1.1?
