### ISSUE TITLE
Allow cylinder_deformation_subspace to return less precise informations

### ISSUE THREAD

**Issue by videlec** [flatsurf/sage-flatsurf#71]
Relations between cylinders could be quite complicated. It is desirable to allow `cylinder_deformation_subspace` to return the smaller one-dimensional subspace spanned by the sum of the circumferences (corresponding to inflating all the cylinders simultaneously).

**Comment by saraedum** [comment]
Is this still relevant? I don't really understand what is the proposal exactly.

**Comment by saraedum** [comment]
Closing. Feel free to reopen if it is still relevant.
