### ISSUE TITLE
Implement get_point_position for Polygon (and not only ConvexPolygon)

### ISSUE THREAD

**Issue by videlec** [flatsurf/sage-flatsurf#93]
The method `ConvexPolygon.get_point_position` returns a relative position of the point with respect to the polygon (eg in the interior, on an edge, at a vertex or outside). It does not exist for `Polygon` even though it does make sense for them. There should exist a general version for `Polygon` (probably going through the triangulation of the polygon).

It might also be desirable to promote `Polygon` to `ConvexPolygon` in the constructors when the input is indeed convex.

**Comment by saraedum** [comment]
> It might also be desirable to promote Polygon to ConvexPolygon in the constructors when the input is indeed convex.

That's been fixed now.
